package entities

import (
	"time"

	"github.com/shopspring/decimal"
)

type Listing struct {
	// Id        uuid.UUID      `json:"id,omitempty"`
	// CreatedAt time.Time      `json:"createdAt,omitempty"`
	// UpdatedAt time.Time      `json:"updatedAt,omitempty"`
	// Meta      map[string]any `json:"meta,omitempty"`

	MlsRecordId                   *int64           `json:"mlsRecordId,string,omitempty"`
	MlsListingId                  *int64           `json:"mlsListingId,string,omitempty"`
	StatusChangeDate              *time.Time       `json:"statusChangeDate,omitempty"`
	FullStreetAddress             *string          `json:"fullStreetAddress,omitempty"`
	HouseNumber                   *string          `json:"houseNumber,omitempty"`
	StreetPreDirection            *string          `json:"streetPreDirection,omitempty"`
	StreetName                    *string          `json:"streetName,omitempty"`
	StreetPostDirection           *string          `json:"streetPostDirection,omitempty"`
	StreetSuffix                  *string          `json:"streetSuffix,omitempty"`
	UnitType                      *string          `json:"unitType,omitempty"`
	UnitNumber                    *string          `json:"unitNumber,omitempty"`
	City                          *string          `json:"city,omitempty"`
	State                         *string          `json:"state,omitempty"`
	Zip5                          *string          `json:"zip5,omitempty"`
	Zip4                          *string          `json:"zip4,omitempty"`
	County                        *string          `json:"county,omitempty"`
	Township                      *string          `json:"township,omitempty"`
	MlsListingAddress             *string          `json:"mlsListingAddress,omitempty"`
	MlsListingCity                *string          `json:"mlsListingCity,omitempty"`
	MlsListingState               *string          `json:"mlsListingState,omitempty"`
	MlsListingZip                 *string          `json:"mlsListingZip,omitempty"`
	MlsListingCountyFips          *string          `json:"mlsListingCountyFips,omitempty"`
	MlsNumber                     *string          `json:"mlsNumber,omitempty"`
	MlsSource                     *string          `json:"mlsSource,omitempty"`
	Ouid                          *string          `json:"ouid,omitempty"`
	ListingStatus                 *string          `json:"listingStatus,omitempty"`
	MlsSoldDate                   *time.Time       `json:"mlsSoldDate,omitempty"`
	MlsSoldPrice                  *int             `json:"mlsSoldPrice,omitempty"`
	AssessorLastSaleDate          *time.Time       `json:"assessorLastSaleDate,omitempty"`
	AssessorLastSaleAmount        *string          `json:"assessorLastSaleAmount,omitempty"`
	MarketValue                   *int             `json:"marketValue,omitempty"`
	MarketValueDate               *time.Time       `json:"marketValueDate,omitempty"`
	AvgMarketPricePerSqFt         *int             `json:"avgMarketPricePerSqFt,omitempty"`
	ListingDate                   *time.Time       `json:"listingDate,omitempty"`
	LatestListingPrice            *int             `json:"latestListingPrice,omitempty"`
	PreviousListingPrice          *int             `json:"previousListingPrice,omitempty"`
	LatestPriceChangeDate         *time.Time       `json:"latestPriceChangeDate,omitempty"`
	PendingDate                   *time.Time       `json:"pendingDate,omitempty"`
	SpecialListingConditions      *string          `json:"specialListingConditions,omitempty"`
	OriginalListingDate           *time.Time       `json:"originalListingDate,omitempty"`
	OriginalListingPrice          *int             `json:"originalListingPrice,omitempty"`
	LeaseOption                   *string          `json:"leaseOption,omitempty"`
	LeaseTerm                     *string          `json:"leaseTerm,omitempty"`
	LeaseIncludes                 *string          `json:"leaseIncludes,omitempty"`
	Concessions                   *string          `json:"concessions,omitempty"`
	ConcessionsAmount             *int             `json:"concessionsAmount,omitempty"`
	ConcessionsComments           *string          `json:"concessionsComments,omitempty"`
	ContingencyDate               *time.Time       `json:"contingencyDate,omitempty"`
	ContingencyDescription        *string          `json:"contingencyDescription,omitempty"`
	MlsPropertyType               *string          `json:"mlsPropertyType,omitempty"`
	MlsPropertySubType            *string          `json:"mlsPropertySubType,omitempty"`
	AsrPropertyType               *string          `json:"asrPropertyType,omitempty"`
	AsrPropertySubType            *string          `json:"asrPropertySubType,omitempty"`
	OwnershipDescription          *string          `json:"ownershipDescription,omitempty"`
	Latitude                      *float64         `json:"latitude,string,omitempty"`
	Longitude                     *float64         `json:"longitude,string,omitempty"`
	Apn                           *string          `json:"apn,omitempty"`
	LegalDescription              *string          `json:"legalDescription,omitempty"`
	LegalSubdivision              *string          `json:"legalSubdivision,omitempty"`
	DaysOnMarket                  *int             `json:"daysOnMarket,omitempty"`
	CumulativeDaysOnMarket        *int             `json:"cumulativeDaysOnMarket,omitempty"`
	ListingAgentFullName          *string          `json:"listingAgentFullName,omitempty"`
	ListingAgentMlsId             *string          `json:"listingAgentMlsId,omitempty"`
	ListingAgentStateLicense      *string          `json:"listingAgentStateLicense,omitempty"`
	ListingAgentAor               *string          `json:"listingAgentAor,omitempty"`
	ListingAgentPreferredPhone    *string          `json:"listingAgentPreferredPhone,omitempty"`
	ListingAgentEmail             *string          `json:"listingAgentEmail,omitempty"`
	ListingOfficeName             *string          `json:"listingOfficeName,omitempty"`
	ListingOfficeMlsId            *string          `json:"listingOfficeMlsId,omitempty"`
	ListingOfficeAor              *string          `json:"listingOfficeAor,omitempty"`
	ListingOfficePhone            *string          `json:"listingOfficePhone,omitempty"`
	ListingOfficeEmail            *string          `json:"listingOfficeEmail,omitempty"`
	ListingCoAgentFullName        *string          `json:"listingCoAgentFullName,omitempty"`
	ListingCoAgentMlsId           *string          `json:"listingCoAgentMlsId,omitempty"`
	ListingCoAgentStateLicense    *string          `json:"listingCoAgentStateLicense,omitempty"`
	ListingCoAgentAor             *string          `json:"listingCoAgentAor,omitempty"`
	ListingCoAgentPreferredPhone  *string          `json:"listingCoAgentPreferredPhone,omitempty"`
	ListingCoAgentEmail           *string          `json:"listingCoAgentEmail,omitempty"`
	ListingCoAgentOfficeName      *string          `json:"listingCoAgentOfficeName,omitempty"`
	ListingCoAgentOfficeMlsId     *string          `json:"listingCoAgentOfficeMlsId,omitempty"`
	ListingCoAgentOfficeAor       *string          `json:"listingCoAgentOfficeAor,omitempty"`
	ListingCoAgentOfficePhone     *string          `json:"listingCoAgentOfficePhone,omitempty"`
	ListingCoAgentOfficeEmail     *string          `json:"listingCoAgentOfficeEmail,omitempty"`
	BuyerAgentFullName            *string          `json:"buyerAgentFullName,omitempty"`
	BuyerAgentMlsId               *string          `json:"buyerAgentMlsId,omitempty"`
	BuyerAgentStateLicense        *string          `json:"buyerAgentStateLicense,omitempty"`
	BuyerAgentAor                 *string          `json:"buyerAgentAor,omitempty"`
	BuyerAgentPreferredPhone      *string          `json:"buyerAgentPreferredPhone,omitempty"`
	BuyerAgentEmail               *string          `json:"buyerAgentEmail,omitempty"`
	BuyerOfficeName               *string          `json:"buyerOfficeName,omitempty"`
	BuyerOfficeMlsId              *string          `json:"buyerOfficeMlsId,omitempty"`
	BuyerOfficeAor                *string          `json:"buyerOfficeAor,omitempty"`
	BuyerOfficePhone              *string          `json:"buyerOfficePhone,omitempty"`
	BuyerOfficeEmail              *string          `json:"buyerOfficeEmail,omitempty"`
	BuyerCoAgentFullName          *string          `json:"buyerCoAgentFullName,omitempty"`
	BuyerCoAgentMlsId             *string          `json:"buyerCoAgentMlsId,omitempty"`
	BuyerCoAgentStateLicense      *string          `json:"buyerCoAgentStateLicense,omitempty"`
	BuyerCoAgentAor               *string          `json:"buyerCoAgentAor,omitempty"`
	BuyerCoAgentPreferredPhone    *string          `json:"buyerCoAgentPreferredPhone,omitempty"`
	BuyerCoAgentEmail             *string          `json:"buyerCoAgentEmail,omitempty"`
	BuyerCoAgentOfficeName        *string          `json:"buyerCoAgentOfficeName,omitempty"`
	BuyerCoAgentOfficeMlsId       *string          `json:"buyerCoAgentOfficeMlsId,omitempty"`
	BuyerCoAgentOfficeAor         *string          `json:"buyerCoAgentOfficeAor,omitempty"`
	BuyerCoAgentOfficePhone       *string          `json:"buyerCoAgentOfficePhone,omitempty"`
	BuyerCoAgentOfficeEmail       *string          `json:"buyerCoAgentOfficeEmail,omitempty"`
	PublicListingRemarks          *string          `json:"publicListingRemarks,omitempty"`
	HasHomeWarranty               *bool            `json:"hasHomeWarranty,omitempty"`
	TaxYearAssessed               *int             `json:"taxYearAssessed,omitempty"`
	TaxAssessedValueTotal         *int             `json:"taxAssessedValueTotal,omitempty"`
	TaxAmount                     *int             `json:"taxAmount,omitempty"`
	TaxAnnualOther                *int             `json:"taxAnnualOther,omitempty"`
	OwnerName                     *string          `json:"ownerName,omitempty"`
	OwnerVesting                  *string          `json:"ownerVesting,omitempty"`
	YearBuilt                     *int             `json:"yearBuilt,omitempty"`
	YearBuiltEffective            *int             `json:"yearBuiltEffective,omitempty"`
	YearBuiltSource               *string          `json:"yearBuiltSource,omitempty"`
	IsNewConstruction             *bool            `json:"isNewConstruction,omitempty"`
	BuilderName                   *string          `json:"builderName,omitempty"`
	HasAdditionalParcels          *bool            `json:"hasAdditionalParcels,omitempty"`
	NumberOfLots                  *int             `json:"numberOfLots,omitempty"`
	LotSizeSquareFeet             *float64         `json:"lotSizeSquareFeet,string,omitempty"`
	LotSizeAcres                  *float64         `json:"lotSizeAcres,string,omitempty"`
	LotSizeSource                 *string          `json:"lotSizeSource,omitempty"`
	LotDimensions                 *string          `json:"lotDimensions,omitempty"`
	LotFeatureList                *string          `json:"lotFeatureList,omitempty"`
	FrontageLength                *string          `json:"frontageLength,omitempty"`
	FrontageType                  *string          `json:"frontageType,omitempty"`
	FrontageRoadType              *string          `json:"frontageRoadType,omitempty"`
	LivingAreaSquareFeet          *int             `json:"livingAreaSquareFeet,omitempty"`
	LivingAreaSource              *string          `json:"livingAreaSource,omitempty"`
	Levels                        *string          `json:"levels,omitempty"`
	Stories                       *decimal.Decimal `json:"stories,omitempty"`
	BuildingStoriesTotal          *decimal.Decimal `json:"buildingStoriesTotal,omitempty"`
	BuildingKeywords              *string          `json:"buildingKeywords,omitempty"`
	BuildingAreaTotal             *int             `json:"buildingAreaTotal,omitempty"`
	NumberOfUnitsTotal            *int             `json:"numberOfUnitsTotal,omitempty"`
	NumberOfBuildings             *int             `json:"numberOfBuildings,omitempty"`
	HasPropertyAttached           *bool            `json:"hasPropertyAttached,omitempty"`
	OtherStructures               *string          `json:"otherStructures,omitempty"`
	RoomsTotal                    *int             `json:"roomsTotal,omitempty"`
	BedroomsTotal                 *int             `json:"bedroomsTotal,omitempty"`
	BathroomsFull                 *decimal.Decimal `json:"bathroomsFull,omitempty"`
	BathroomsHalf                 *int             `json:"bathroomsHalf,omitempty"`
	BathroomsQuarter              *int             `json:"bathroomsQuarter,omitempty"`
	BathroomsThreeQuarters        *int             `json:"bathroomsThreeQuarters,omitempty"`
	BasementFeatures              *string          `json:"basementFeatures,omitempty"`
	BelowGradeSquareFeet          *int             `json:"belowGradeSquareFeet,omitempty"`
	BasementTotalSqFt             *int             `json:"basementTotalSqFt,omitempty"`
	BasementFinishedSqFt          *int             `json:"basementFinishedSqFt,omitempty"`
	BasementUnfinishedSqFt        *int             `json:"basementUnfinishedSqFt,omitempty"`
	PropertyCondition             *string          `json:"propertyCondition,omitempty"`
	HasNeededRepairs              *bool            `json:"hasNeededRepairs,omitempty"`
	RepairsDescription            *string          `json:"repairsDescription,omitempty"`
	Disclosures                   *string          `json:"disclosures,omitempty"`
	ConstructionMaterials         *string          `json:"constructionMaterials,omitempty"`
	HasGarage                     *bool            `json:"hasGarage,omitempty"`
	HasAttachedGarage             *bool            `json:"hasAttachedGarage,omitempty"`
	GarageSpaces                  *decimal.Decimal `json:"garageSpaces,omitempty"`
	HasCarport                    *bool            `json:"hasCarport,omitempty"`
	CarportSpaces                 *float64         `json:"carportSpaces,string,omitempty"`
	ParkingFeatures               *string          `json:"parkingFeatures,omitempty"`
	ParkingOther                  *string          `json:"parkingOther,omitempty"`
	OpenParkingSpaces             *float64         `json:"openParkingSpaces,string,omitempty"`
	ParkingTotal                  *float64         `json:"parkingTotal,string,omitempty"`
	HasPrivatePool                *bool            `json:"hasPrivatePool,omitempty"`
	PoolFeatures                  *string          `json:"poolFeatures,omitempty"`
	Occupancy                     *string          `json:"occupancy,omitempty"`
	HasView                       *bool            `json:"hasView,omitempty"`
	View                          *string          `json:"view,omitempty"`
	Topography                    *string          `json:"topography,omitempty"`
	HasHeating                    *bool            `json:"hasHeating,omitempty"`
	HeatingFeatures               *string          `json:"heatingFeatures,omitempty"`
	HasCooling                    *bool            `json:"hasCooling,omitempty"`
	Cooling                       *string          `json:"cooling,omitempty"`
	HasFireplace                  *bool            `json:"hasFireplace,omitempty"`
	Fireplace                     *string          `json:"fireplace,omitempty"`
	FireplaceNumber               *float64         `json:"fireplaceNumber,string,omitempty"`
	FoundationFeatures            *string          `json:"foundationFeatures,omitempty"`
	Roof                          *string          `json:"roof,omitempty"`
	ArchitecturalStyleFeatures    *string          `json:"architecturalStyleFeatures,omitempty"`
	PatioAndPorchFeatures         *string          `json:"patioAndPorchFeatures,omitempty"`
	Utilities                     *string          `json:"utilities,omitempty"`
	ElectricIncluded              *bool            `json:"electricIncluded,omitempty"`
	ElectricDescription           *string          `json:"electricDescription,omitempty"`
	WaterIncluded                 *bool            `json:"waterIncluded,omitempty"`
	WaterSource                   *string          `json:"waterSource,omitempty"`
	Sewer                         *string          `json:"sewer,omitempty"`
	GasDescription                *string          `json:"gasDescription,omitempty"`
	OtherEquipmentIncluded        *string          `json:"otherEquipmentIncluded,omitempty"`
	LaundryFeatures               *string          `json:"laundryFeatures,omitempty"`
	Appliances                    *string          `json:"appliances,omitempty"`
	InteriorFeatures              *string          `json:"interiorFeatures,omitempty"`
	ExteriorFeatures              *string          `json:"exteriorFeatures,omitempty"`
	FencingFeatures               *string          `json:"fencingFeatures,omitempty"`
	PetsAllowed                   *string          `json:"petsAllowed,omitempty"`
	HorseZoning                   *bool            `json:"horseZoning,omitempty"`
	SeniorCommunity               *bool            `json:"seniorCommunity,omitempty"`
	WaterbodyName                 *string          `json:"waterbodyName,omitempty"`
	IsWaterfront                  *bool            `json:"isWaterfront,omitempty"`
	WaterfrontFeatures            *string          `json:"waterfrontFeatures,omitempty"`
	ZoningCode                    *string          `json:"zoningCode,omitempty"`
	ZoningDescription             *string          `json:"zoningDescription,omitempty"`
	CurrentUse                    *string          `json:"currentUse,omitempty"`
	PossibleUse                   *string          `json:"possibleUse,omitempty"`
	HasAssociation                *bool            `json:"hasAssociation,omitempty"`
	Association1Name              *string          `json:"association1Name,omitempty"`
	Association1Phone             *string          `json:"association1Phone,omitempty"`
	Association1Fee               *int             `json:"association1Fee,omitempty"`
	Association1FeeFrequency      *string          `json:"association1FeeFrequency,omitempty"`
	Association2Name              *string          `json:"association2Name,omitempty"`
	Association2Phone             *string          `json:"association2Phone,omitempty"`
	Association2Fee               *int             `json:"association2Fee,omitempty"`
	Association2FeeFrequency      *string          `json:"association2FeeFrequency,omitempty"`
	AssociationFeeIncludes        *string          `json:"associationFeeIncludes,omitempty"`
	AssociationAmenities          *string          `json:"associationAmenities,omitempty"`
	SchoolElementary              *string          `json:"schoolElementary,omitempty"`
	SchoolElementaryDistrict      *string          `json:"schoolElementaryDistrict,omitempty"`
	SchoolMiddle                  *string          `json:"schoolMiddle,omitempty"`
	SchoolMiddleDistrict          *string          `json:"schoolMiddleDistrict,omitempty"`
	SchoolHigh                    *string          `json:"schoolHigh,omitempty"`
	SchoolHighDistrict            *string          `json:"schoolHighDistrict,omitempty"`
	HasGreenVerification          *bool            `json:"hasGreenVerification,omitempty"`
	GreenBuildingVerificationType *string          `json:"greenBuildingVerificationType,omitempty"`
	GreenEnergyEfficient          *string          `json:"greenEnergyEfficient,omitempty"`
	GreenEnergyGeneration         *string          `json:"greenEnergyGeneration,omitempty"`
	GreenIndoorAirQuality         *string          `json:"greenIndoorAirQuality,omitempty"`
	GreenLocation                 *string          `json:"greenLocation,omitempty"`
	GreenSustainability           *string          `json:"greenSustainability,omitempty"`
	GreenWaterConservation        *string          `json:"greenWaterConservation,omitempty"`
	HasLandLease                  *bool            `json:"hasLandLease,omitempty"`
	LandLeaseAmount               *decimal.Decimal `json:"landLeaseAmount,omitempty"`
	LandLeaseAmountFrequency      *string          `json:"landLeaseAmountFrequency,omitempty"`
	LandLeaseExpirationDate       *time.Time       `json:"landLeaseExpirationDate,omitempty"`
	CapRate                       *decimal.Decimal `json:"capRate,omitempty"`
	GrossIncome                   *decimal.Decimal `json:"grossIncome,omitempty"`
	IncomeIncludes                *string          `json:"incomeIncludes,omitempty"`
	GrossScheduledIncome          *decimal.Decimal `json:"grossScheduledIncome,omitempty"`
	NetOperatingIncome            *decimal.Decimal `json:"netOperatingIncome,omitempty"`
	TotalActualRent               *decimal.Decimal `json:"totalActualRent,omitempty"`
	ExistingLeaseType             *string          `json:"existingLeaseType,omitempty"`
	FinancialDataSource           *string          `json:"financialDataSource,omitempty"`
	HasRentControl                *bool            `json:"hasRentControl,omitempty"`
	UnitTypeDescription           *string          `json:"unitTypeDescription,omitempty"`
	UnitTypeFurnished             *string          `json:"unitTypeFurnished,omitempty"`
	NumberOfUnitsLeased           *float64         `json:"numberOfUnitsLeased,string,omitempty"`
	NumberOfUnitsMoMo             *float64         `json:"numberOfUnitsMoMo,string,omitempty"`
	NumberOfUnitsVacant           *float64         `json:"numberOfUnitsVacant,string,omitempty"`
	VacancyAllowance              *float64         `json:"vacancyAllowance,string,omitempty"`
	VacancyAllowanceRate          *float64         `json:"vacancyAllowanceRate,string,omitempty"`
	OperatingExpense              *decimal.Decimal `json:"operatingExpense,omitempty"`
	CableTvExpense                *decimal.Decimal `json:"cableTvExpense,omitempty"`
	ElectricExpense               *decimal.Decimal `json:"electricExpense,omitempty"`
	FuelExpense                   *decimal.Decimal `json:"fuelExpense,omitempty"`
	FurnitureReplacementExpense   *decimal.Decimal `json:"furnitureReplacementExpense,omitempty"`
	GardenerExpense               *decimal.Decimal `json:"gardenerExpense,omitempty"`
	InsuranceExpense              *decimal.Decimal `json:"insuranceExpense,omitempty"`
	OperatingExpenseIncludes      *string          `json:"operatingExpenseIncludes,omitempty"`
	LicensesExpense               *decimal.Decimal `json:"licensesExpense,omitempty"`
	MaintenanceExpense            *decimal.Decimal `json:"maintenanceExpense,omitempty"`
	ManagerExpense                *decimal.Decimal `json:"managerExpense,omitempty"`
	NewTaxesExpense               *decimal.Decimal `json:"newTaxesExpense,omitempty"`
	OtherExpense                  *decimal.Decimal `json:"otherExpense,omitempty"`
	PestControlExpense            *decimal.Decimal `json:"pestControlExpense,omitempty"`
	PoolExpense                   *decimal.Decimal `json:"poolExpense,omitempty"`
	ProfessionalManagementExpense *decimal.Decimal `json:"professionalManagementExpense,omitempty"`
	SuppliesExpense               *decimal.Decimal `json:"suppliesExpense,omitempty"`
	TrashExpense                  *decimal.Decimal `json:"trashExpense,omitempty"`
	WaterSewerExpense             *decimal.Decimal `json:"waterSewerExpense,omitempty"`
	WorkmansCompensationExpense   *decimal.Decimal `json:"workmansCompensationExpense,omitempty"`
	OwnerPays                     *string          `json:"ownerPays,omitempty"`
	TenantPays                    *string          `json:"tenantPays,omitempty"`
	ListingMarketingUrl           *string          `json:"listingMarketingUrl,omitempty"`
	PhotosCount                   *int             `json:"photosCount,omitempty"`
	PhotoKey                      *string          `json:"photoKey,omitempty"`
	PhotoUrlPrefix                *string          `json:"photoUrlPrefix,omitempty"`
	RN                            int              `json:"-"`
}
