package entities

import (
	"time"

	"github.com/shopspring/decimal"
)

type Recorder struct {
	// Id        uuid.UUID      `json:"id,omitempty"`
	// CreatedAt time.Time      `json:"createdAt,omitempty"`
	// UpdatedAt time.Time      `json:"updatedAt,omitempty"`
	// Meta      map[string]any `json:"meta,omitempty"`

	TransactionId                    *int64           `json:"transactionId,string,omitempty"`
	RecordingStateCode               *string          `json:"recordingStateCode,omitempty"`
	RecordingCountyName              *string          `json:"recordingCountyName,omitempty"`
	RecordingJurisdictionName        *string          `json:"recordingJurisdictionName,omitempty"`
	RecordingCountyFips              *string          `json:"recordingCountyFips,omitempty"`
	DocumentTypeCode                 *string          `json:"documentTypeCode,omitempty"`
	DocumentNumber                   *string          `json:"documentNumber,omitempty"`
	DocumentNumberLegacy             *string          `json:"documentNumberLegacy,omitempty"`
	InstrumentNumber                 *string          `json:"instrumentNumber,omitempty"`
	Book                             *string          `json:"book,omitempty"`
	Page                             *string          `json:"page,omitempty"`
	InstrumentDate                   *time.Time       `json:"instrumentDate,omitempty"`
	RecordingDate                    *time.Time       `json:"recordingDate,omitempty"`
	TransactionType                  *string          `json:"transactionType,omitempty"`
	PurchaseTypeCode                 *int             `json:"purchaseTypeCode,omitempty"`
	IsForeclosureAuction             *bool            `json:"isForeclosureAuction,omitempty"`
	DistressCircumstanceCode         *int             `json:"distressCircumstanceCode,omitempty"`
	IsQuitclaim                      *bool            `json:"isQuitclaim,omitempty"`
	MultiParcel                      *int             `json:"multiParcel,omitempty"`
	ArmsLength                       *int             `json:"armsLength,omitempty"`
	PartialInterest                  *string          `json:"partialInterest,omitempty"`
	TransferAmount                   *decimal.Decimal `json:"transferAmount,omitempty"`
	TransferAmountAccuracy           *string          `json:"transferAmountAccuracy,omitempty"`
	TransferTaxTotal                 *decimal.Decimal `json:"transferTaxTotal,omitempty"`
	TransferTaxCity                  *decimal.Decimal `json:"transferTaxCity,omitempty"`
	TransferTaxCounty                *decimal.Decimal `json:"transferTaxCounty,omitempty"`
	Grantor1FullName                 *string          `json:"grantor1FullName,omitempty"`
	Grantor1FirstName                *string          `json:"grantor1FirstName,omitempty"`
	Grantor1MiddleName               *string          `json:"grantor1MiddleName,omitempty"`
	Grantor1LastName                 *string          `json:"grantor1LastName,omitempty"`
	Grantor1Suffix                   *string          `json:"grantor1Suffix,omitempty"`
	Grantor1EntityType               *string          `json:"grantor1EntityType,omitempty"`
	Grantor1OwnerType                *string          `json:"grantor1OwnerType,omitempty"`
	Grantor2FullName                 *string          `json:"grantor2FullName,omitempty"`
	Grantor2FirstName                *string          `json:"grantor2FirstName,omitempty"`
	Grantor2MiddleName               *string          `json:"grantor2MiddleName,omitempty"`
	Grantor2LastName                 *string          `json:"grantor2LastName,omitempty"`
	Grantor2Suffix                   *string          `json:"grantor2Suffix,omitempty"`
	Grantor2EntityType               *string          `json:"grantor2EntityType,omitempty"`
	Grantor2OwnerType                *string          `json:"grantor2OwnerType,omitempty"`
	Grantor3FullName                 *string          `json:"grantor3FullName,omitempty"`
	Grantor3FirstName                *string          `json:"grantor3FirstName,omitempty"`
	Grantor3MiddleName               *string          `json:"grantor3MiddleName,omitempty"`
	Grantor3LastName                 *string          `json:"grantor3LastName,omitempty"`
	Grantor3Suffix                   *string          `json:"grantor3Suffix,omitempty"`
	Grantor3EntityType               *string          `json:"grantor3EntityType,omitempty"`
	Grantor4FullName                 *string          `json:"grantor4FullName,omitempty"`
	Grantor4FirstName                *string          `json:"grantor4FirstName,omitempty"`
	Grantor4MiddleName               *string          `json:"grantor4MiddleName,omitempty"`
	Grantor4LastName                 *string          `json:"grantor4LastName,omitempty"`
	Grantor4Suffix                   *string          `json:"grantor4Suffix,omitempty"`
	Grantor4EntityType               *string          `json:"grantor4EntityType,omitempty"`
	GrantorFullStreetAddress         *string          `json:"grantorFullStreetAddress,omitempty"`
	GrantorHouseNumber               *string          `json:"grantorHouseNumber,omitempty"`
	GrantorStreetPreDirection        *string          `json:"grantorStreetPreDirection,omitempty"`
	GrantorStreetName                *string          `json:"grantorStreetName,omitempty"`
	GrantorStreetPostDirection       *string          `json:"grantorStreetPostDirection,omitempty"`
	GrantorStreetSuffix              *string          `json:"grantorStreetSuffix,omitempty"`
	GrantorUnitType                  *string          `json:"grantorUnitType,omitempty"`
	GrantorUnitValue                 *string          `json:"grantorUnitValue,omitempty"`
	GrantorCity                      *string          `json:"grantorCity,omitempty"`
	GrantorState                     *string          `json:"grantorState,omitempty"`
	GrantorZip5                      *string          `json:"grantorZip5,omitempty"`
	GrantorZip4                      *string          `json:"grantorZip4,omitempty"`
	GrantorCarrierRoute              *string          `json:"grantorCarrierRoute,omitempty"`
	GrantorAddressFormat             *string          `json:"grantorAddressFormat,omitempty"`
	GrantorAddressPrivacy            *bool            `json:"grantorAddressPrivacy,omitempty"`
	Grantee1FullName                 *string          `json:"grantee1FullName,omitempty"`
	Grantee1FirstName                *string          `json:"grantee1FirstName,omitempty"`
	Grantee1MiddleName               *string          `json:"grantee1MiddleName,omitempty"`
	Grantee1LastName                 *string          `json:"grantee1LastName,omitempty"`
	Grantee1Suffix                   *string          `json:"grantee1Suffix,omitempty"`
	Grantee1EntityType               *string          `json:"grantee1EntityType,omitempty"`
	Grantee1OwnerType                *string          `json:"grantee1OwnerType,omitempty"`
	Grantee2FullName                 *string          `json:"grantee2FullName,omitempty"`
	Grantee2FirstName                *string          `json:"grantee2FirstName,omitempty"`
	Grantee2MiddleName               *string          `json:"grantee2MiddleName,omitempty"`
	Grantee2LastName                 *string          `json:"grantee2LastName,omitempty"`
	Grantee2Suffix                   *string          `json:"grantee2Suffix,omitempty"`
	Grantee2EntityType               *string          `json:"grantee2EntityType,omitempty"`
	GranteeVesting1                  *string          `json:"granteeVesting1,omitempty"`
	Grantee3FullName                 *string          `json:"grantee3FullName,omitempty"`
	Grantee3FirstName                *string          `json:"grantee3FirstName,omitempty"`
	Grantee3MiddleName               *string          `json:"grantee3MiddleName,omitempty"`
	Grantee3LastName                 *string          `json:"grantee3LastName,omitempty"`
	Grantee3Suffix                   *string          `json:"grantee3Suffix,omitempty"`
	Grantee3EntityType               *string          `json:"grantee3EntityType,omitempty"`
	Grantee4FullName                 *string          `json:"grantee4FullName,omitempty"`
	Grantee4FirstName                *string          `json:"grantee4FirstName,omitempty"`
	Grantee4MiddleName               *string          `json:"grantee4MiddleName,omitempty"`
	Grantee4LastName                 *string          `json:"grantee4LastName,omitempty"`
	Grantee4Suffix                   *string          `json:"grantee4Suffix,omitempty"`
	Grantee4EntityType               *string          `json:"grantee4EntityType,omitempty"`
	GranteeMailCareOfName            *string          `json:"granteeMailCareOfName,omitempty"`
	GranteeEntityCount               *int             `json:"granteeEntityCount,omitempty"`
	GranteeVesting2                  *string          `json:"granteeVesting2,omitempty"`
	IsGranteeInvestor                *bool            `json:"isGranteeInvestor,omitempty"`
	GranteeMailFullStreetAddress     *string          `json:"granteeMailFullStreetAddress,omitempty"`
	GranteeMailHouseNumber           *string          `json:"granteeMailHouseNumber,omitempty"`
	GranteeMailStreetPreDirection    *string          `json:"granteeMailStreetPreDirection,omitempty"`
	GranteeMailStreetName            *string          `json:"granteeMailStreetName,omitempty"`
	GranteeMailStreetPostDirection   *string          `json:"granteeMailStreetPostDirection,omitempty"`
	GranteeMailStreetSuffix          *string          `json:"granteeMailStreetSuffix,omitempty"`
	GranteeMailUnitType              *string          `json:"granteeMailUnitType,omitempty"`
	GranteeMailUnitValue             *string          `json:"granteeMailUnitValue,omitempty"`
	GranteeMailCity                  *string          `json:"granteeMailCity,omitempty"`
	GranteeMailState                 *string          `json:"granteeMailState,omitempty"`
	GranteeMailZip5                  *string          `json:"granteeMailZip5,omitempty"`
	GranteeMailZip4                  *string          `json:"granteeMailZip4,omitempty"`
	GranteeMailCarrierRoute          *string          `json:"granteeMailCarrierRoute,omitempty"`
	GranteeMailAddressFormat         *string          `json:"granteeMailAddressFormat,omitempty"`
	GranteeMailAddressPrivacy        *bool            `json:"granteeMailAddressPrivacy,omitempty"`
	GranteeGrantorRelationshipCode   *string          `json:"granteeGrantorRelationshipCode,omitempty"`
	TitleCompanyCode                 *string          `json:"titleCompanyCode,omitempty"`
	TitleCompanyName                 *string          `json:"titleCompanyName,omitempty"`
	TitleCompanyRaw                  *string          `json:"titleCompanyRaw,omitempty"`
	LegalDescriptionPart1            *string          `json:"legalDescriptionPart1,omitempty"`
	LegalDescriptionPart2            *string          `json:"legalDescriptionPart2,omitempty"`
	LegalDescriptionPart3            *string          `json:"legalDescriptionPart3,omitempty"`
	LegalDescriptionPart4            *string          `json:"legalDescriptionPart4,omitempty"`
	LegalRange                       *string          `json:"legalRange,omitempty"`
	LegalTownship                    *string          `json:"legalTownship,omitempty"`
	LegalSection                     *string          `json:"legalSection,omitempty"`
	LegalDistrict                    *string          `json:"legalDistrict,omitempty"`
	LegalSubDivision                 *string          `json:"legalSubDivision,omitempty"`
	LegalTract                       *string          `json:"legalTract,omitempty"`
	LegalBlock                       *string          `json:"legalBlock,omitempty"`
	LegalLot                         *string          `json:"legalLot,omitempty"`
	LegalUnit                        *string          `json:"legalUnit,omitempty"`
	LegalPlatMapBook                 *string          `json:"legalPlatMapBook,omitempty"`
	LegalPlatMapPage                 *string          `json:"legalPlatMapPage,omitempty"`
	Apn                              *string          `json:"apn,omitempty"`
	ApnOriginal                      *string          `json:"apnOriginal,omitempty"`
	FullStreetAddress                *string          `json:"fullStreetAddress,omitempty"`
	HouseNumber                      *string          `json:"houseNumber,omitempty"`
	StreetPreDirection               *string          `json:"streetPreDirection,omitempty"`
	StreetName                       *string          `json:"streetName,omitempty"`
	StreetPostDirection              *string          `json:"streetPostDirection,omitempty"`
	StreetSuffix                     *string          `json:"streetSuffix,omitempty"`
	UnitType                         *string          `json:"unitType,omitempty"`
	UnitNumber                       *string          `json:"unitNumber,omitempty"`
	City                             *string          `json:"city,omitempty"`
	State                            *string          `json:"state,omitempty"`
	Zip5                             *string          `json:"zip5,omitempty"`
	Zip4                             *string          `json:"zip4,omitempty"`
	PropertyCarrierRoute             *string          `json:"propertyCarrierRoute,omitempty"`
	PropertyAddressFormat            *string          `json:"propertyAddressFormat,omitempty"`
	PropertyAddressPrivacy           *bool            `json:"propertyAddressPrivacy,omitempty"`
	RecorderMapReference             *string          `json:"recorderMapReference,omitempty"`
	PropertyUseGroup                 *string          `json:"propertyUseGroup,omitempty"`
	PropertyUseStandardized          *string          `json:"propertyUseStandardized,omitempty"`
	Mortgage1DocumentNumber          *string          `json:"mortgage1DocumentNumber,omitempty"`
	Mortgage1DocumentNumberLegacy    *string          `json:"mortgage1DocumentNumberLegacy,omitempty"`
	Mortgage1InstrumentNumber        *string          `json:"mortgage1InstrumentNumber,omitempty"`
	Mortgage1Book                    *string          `json:"mortgage1Book,omitempty"`
	Mortgage1Page                    *string          `json:"mortgage1Page,omitempty"`
	Mortgage1RecordingDate           *time.Time       `json:"mortgage1RecordingDate,omitempty"`
	Mortgage1Type                    *string          `json:"mortgage1Type,omitempty"`
	Mortgage1Amount                  *int             `json:"mortgage1Amount,omitempty"`
	Mortgage1LenderCode              *int             `json:"mortgage1LenderCode,omitempty"`
	Mortgage1LenderName              *string          `json:"mortgage1LenderName,omitempty"`
	Mortgage1LenderFirstName         *string          `json:"mortgage1LenderFirstName,omitempty"`
	Mortgage1LenderLastName          *string          `json:"mortgage1LenderLastName,omitempty"`
	Mortgage1LenderAddress           *string          `json:"mortgage1LenderAddress,omitempty"`
	Mortgage1LenderCity              *string          `json:"mortgage1LenderCity,omitempty"`
	Mortgage1LenderState             *string          `json:"mortgage1LenderState,omitempty"`
	Mortgage1LenderZip               *string          `json:"mortgage1LenderZip,omitempty"`
	Mortgage1LenderZip4              *string          `json:"mortgage1LenderZip4,omitempty"`
	Mortgage1LenderEntityType        *string          `json:"mortgage1LenderEntityType,omitempty"`
	IsMortgage1SellerCarryBack       *bool            `json:"isMortgage1SellerCarryBack,omitempty"`
	Mortgage1Term                    *int             `json:"mortgage1Term,omitempty"`
	Mortgage1TermType                *string          `json:"mortgage1TermType,omitempty"`
	Mortgage1TermDate                *time.Time       `json:"mortgage1TermDate,omitempty"`
	HasMortgage1PrepaymentPenalty    *bool            `json:"hasMortgage1PrepaymentPenalty,omitempty"`
	Mortgage1PrepaymentTerm          *string          `json:"mortgage1PrepaymentTerm,omitempty"`
	Mortgage1InterestRateType        *string          `json:"mortgage1InterestRateType,omitempty"`
	Mortgage1InterestRate            *decimal.Decimal `json:"mortgage1InterestRate,omitempty"`
	Mortgage1InitialInterestType     *string          `json:"mortgage1InitialInterestType,omitempty"`
	Mortgage1FixedStepConversionRate *string          `json:"mortgage1FixedStepConversionRate,omitempty"`
	HasMortgage1AdjustableRateRider  *bool            `json:"hasMortgage1AdjustableRateRider,omitempty"`
	Mortgage1InterestChangeYear      *int             `json:"mortgage1InterestChangeYear,omitempty"`
	Mortgage1InterestChangeMonth     *int             `json:"mortgage1InterestChangeMonth,omitempty"`
	Mortgage1InterestChangeDay       *int             `json:"mortgage1InterestChangeDay,omitempty"`
	Mortgage1MinFirstChangeRate      *decimal.Decimal `json:"mortgage1MinFirstChangeRate,omitempty"`
	Mortgage1MaxFirstChangeRate      *decimal.Decimal `json:"mortgage1MaxFirstChangeRate,omitempty"`
	Mortgage1InterestChangeFrequency *string          `json:"mortgage1InterestChangeFrequency,omitempty"`
	Mortgage1InterestMargin          *int             `json:"mortgage1InterestMargin,omitempty"`
	Mortgage1InterestIndex           *decimal.Decimal `json:"mortgage1InterestIndex,omitempty"`
	Mortgage1MaxInterestRate         *decimal.Decimal `json:"mortgage1MaxInterestRate,omitempty"`
	Mortgage1AdjustableRateIndex     *string          `json:"mortgage1AdjustableRateIndex,omitempty"`
	IsMortgage1InterestOnly          *bool            `json:"isMortgage1InterestOnly,omitempty"`
	Mortgage1InterestOnlyPeriod      *string          `json:"mortgage1InterestOnlyPeriod,omitempty"`
	Mortgage2DocumentNumber          *string          `json:"mortgage2DocumentNumber,omitempty"`
	Mortgage2DocumentNumberLegacy    *string          `json:"mortgage2DocumentNumberLegacy,omitempty"`
	Mortgage2InstrumentNumber        *string          `json:"mortgage2InstrumentNumber,omitempty"`
	Mortgage2Book                    *string          `json:"mortgage2Book,omitempty"`
	Mortgage2Page                    *string          `json:"mortgage2Page,omitempty"`
	Mortgage2RecordingDate           *time.Time       `json:"mortgage2RecordingDate,omitempty"`
	Mortgage2Type                    *string          `json:"mortgage2Type,omitempty"`
	Mortgage2Amount                  *int             `json:"mortgage2Amount,omitempty"`
	Mortgage2LenderCode              *int             `json:"mortgage2LenderCode,omitempty"`
	Mortgage2LenderName              *string          `json:"mortgage2LenderName,omitempty"`
	Mortgage2LenderFirstName         *string          `json:"mortgage2LenderFirstName,omitempty"`
	Mortgage2LenderLastName          *string          `json:"mortgage2LenderLastName,omitempty"`
	Mortgage2LenderAddress           *string          `json:"mortgage2LenderAddress,omitempty"`
	Mortgage2LenderCity              *string          `json:"mortgage2LenderCity,omitempty"`
	Mortgage2LenderState             *string          `json:"mortgage2LenderState,omitempty"`
	Mortgage2LenderZip               *string          `json:"mortgage2LenderZip,omitempty"`
	Mortgage2LenderZip4              *string          `json:"mortgage2LenderZip4,omitempty"`
	Mortgage2LenderEntityType        *string          `json:"mortgage2LenderEntityType,omitempty"`
	IsMortgage2SellerCarryBack       *bool            `json:"isMortgage2SellerCarryBack,omitempty"`
	Mortgage2Term                    *int             `json:"mortgage2Term,omitempty"`
	Mortgage2TermType                *string          `json:"mortgage2TermType,omitempty"`
	Mortgage2TermDate                *time.Time       `json:"mortgage2TermDate,omitempty"`
	HasMortgage2PrepaymentPenalty    *bool            `json:"hasMortgage2PrepaymentPenalty,omitempty"`
	Mortgage2PrepaymentTerm          *string          `json:"mortgage2PrepaymentTerm,omitempty"`
	Mortgage2InterestRateType        *string          `json:"mortgage2InterestRateType,omitempty"`
	Mortgage2InterestRate            *decimal.Decimal `json:"mortgage2InterestRate,omitempty"`
	Mortgage2InitialInterestType     *string          `json:"mortgage2InitialInterestType,omitempty"`
	Mortgage2FixedStepConversionRate *string          `json:"mortgage2FixedStepConversionRate,omitempty"`
	HasMortgage2AdjustableRateRider  *bool            `json:"hasMortgage2AdjustableRateRider,omitempty"`
	Mortgage2InterestChangeYear      *int             `json:"mortgage2InterestChangeYear,omitempty"`
	Mortgage2InterestChangeMonth     *int             `json:"mortgage2InterestChangeMonth,omitempty"`
	Mortgage2InterestChangeDay       *int             `json:"mortgage2InterestChangeDay,omitempty"`
	Mortgage2MinFirstChangeRate      *decimal.Decimal `json:"mortgage2MinFirstChangeRate,omitempty"`
	Mortgage2MaxFirstChangeRate      *decimal.Decimal `json:"mortgage2MaxFirstChangeRate,omitempty"`
	Mortgage2InterestChangeFrequency *string          `json:"mortgage2InterestChangeFrequency,omitempty"`
	Mortgage2InterestMargin          *int             `json:"mortgage2InterestMargin,omitempty"`
	Mortgage2InterestIndex           *decimal.Decimal `json:"mortgage2InterestIndex,omitempty"`
	Mortgage2MaxInterestRate         *decimal.Decimal `json:"mortgage2MaxInterestRate,omitempty"`
	Mortgage2AdjustableRateIndex     *string          `json:"mortgage2AdjustableRateIndex,omitempty"`
	IsMortgage2InterestOnly          *bool            `json:"isMortgage2InterestOnly,omitempty"`
	Mortgage2InterestOnlyPeriod      *string          `json:"mortgage2InterestOnlyPeriod,omitempty"`
	PurchaseDownPayment              *int             `json:"purchaseDownPayment,omitempty"`
	PurchaseLoanToValue              *decimal.Decimal `json:"purchaseLoanToValue,omitempty"`
}
