# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

# Ordered by directories path.
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/code/go/abodemine"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories:
      - "/code/python/abodemine"
    schedule:
      interval: "weekly"

  # - package-ecosystem: "cargo"
  #   directories:
  #     - "/code/rust/abodemine/crates/*"
  #   schedule:
  #     interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/code/typescript"
    schedule:
      interval: "weekly"
