[project]
name = "abodemine"
version = "0.1.0"
requires-python = "==3.11.*"
dependencies = ["PyYAML==6.0.2"]

[project.optional-dependencies]
dev = ["bcrypt==4.3.0", "pydantic==2.11.5"]

[dependency-groups]
dev = [
    "csvkit>=2.1.0",
]
